# Railway.toml - Frontend Configuration
[build]
builder = "NIXPACKS"
buildCommand = "cd frontend && npm install && npm run build"

[deploy]
startCommand = "cd frontend && npx serve -s build -l 3000"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
